
#apiVersion: v1
#data:
#  elastic: MTIz
#kind: Secret
#metadata:
#  name: quickstart-es-elastic-user
#  namespace: default
#type: Opaque

apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: elastic    # required field for kubernetes.io/basic-auth
  password: mypass # required field for kubernetes.io/basic-auth
  roles: superuser