apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: joseacunacarrera/api
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 5000
  externalIPs:
    - 1.2.4.120